name: CodeFundi Build Diagnosis AI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run CodeFundi Build Diagnosis AI
        uses: codefundi/build-diagnosis-ai@v1
        with:
          api-key: ${{ secrets.CODEFUNDI_API_KEY }}
          option1: value1
          option2: value2
